baseURL = "https://guide.xeneta.com/"
googleAnalytics = "UA-137344312-1"
languageCode = "en-us"
title = "Xeneta Guide"
theme = "hugo-theme-learn"
showVisitedLinks = false
disableLanguageSwitchingButton = true
disableNextPrev = true
disableAssetsBusting = false
publishDir = "../../docs"
disableShortcutsTitle = true

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> Help Center"
identifier = "xensup"
url = "https://support.xeneta.com"
weight = 10

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> API Reference"
identifier = "xenapi"
url = "https://xeneta.github.io/XenDoc/"
weight = 20

[outputs]
home = [ "HTML", "RSS", "JSON"]