baseURL = "https://guide.xeneta.net/"
googleAnalytics = "UA-137344312-1"
languageCode = "en-us"
title = "Xeneta Guide"
theme = "hugo-theme-learn"
showVisitedLinks = false
disableLanguageSwitchingButton = true
disableNextPrev = true
disableAssetsBusting = false
publishDir = "../../docs"

[[menu.shortcuts]]
name = "<i class='fas fa-book'></i> Help Center"
identifier = "xensup"
url = "https://support.xeneta.com"
weight = 10

[outputs]
home = [ "HTML", "RSS", "JSON"]