baseURL = "https://xeneta.github.io/XenGuide/"
languageCode = "en-us"
title = "Xeneta Guide"
theme = "hugo-theme-learn"
showVisitedLinks = false
disableLanguageSwitchingButton = true
disableNextPrev = true
disableAssetsBusting = false
publishDir = "../../docs"

[outputs]
home = [ "HTML", "RSS", "JSON"]